# Claude Code Orchestrator - User Workflow
#
# Add this file to YOUR repository at:
# .github/workflows/orchestrator.yml
#
# Required secrets:
#   - CLAUDE_CONFIGS: JSON array of Claude API configurations
#     Example: [{"env":{"ANTHROPIC_AUTH_TOKEN":"your-key","ANTHROPIC_BASE_URL":"https://api.z.ai/api/anthropic"}}]
#   - CCO_PAT: GitHub PAT with repo permissions
#
# Then add the 'orchestrator' label to any issue to trigger!

name: Claude Orchestrator

on:
  issues:
    types: [labeled]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  orchestrate:
    if: github.event.label.name == 'orchestrator'
    uses: mohsen1/claude-orchestrator-action/.github/workflows/orchestrate.yml@main
    with:
      issue_number: ${{ github.event.issue.number }}
    secrets:
      CLAUDE_CONFIGS: ${{ secrets.CLAUDE_CONFIGS }}
      CCO_PAT: ${{ secrets.CCO_PAT }}
