# Claude Code Orchestrator - User Workflow
#
# Add this file to YOUR repository at:
# .github/workflows/orchestrator.yml
#
# Required secrets:
#   - CLAUDE_CONFIGS: JSON array of Claude API configurations
#     Example: [{"env":{"ANTHROPIC_AUTH_TOKEN":"your-key","ANTHROPIC_BASE_URL":"https://api.z.ai/api/anthropic"}}]
#   - CCO_PAT: GitHub PAT with repo permissions
#
# Then add the 'orchestrator' label to any issue to trigger!

name: Claude Orchestrator

on:
  issues:
    types: [labeled]
  pull_request_review:
    types: [submitted]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  # Main orchestration - triggered by adding 'orchestrator' label to an issue
  orchestrate:
    if: github.event_name == 'issues' && github.event.label.name == 'orchestrator'
    uses: mohsen1/claude-orchestrator-action/.github/workflows/orchestrate.yml@main
    with:
      issue_number: ${{ github.event.issue.number }}
      # Optional: customize these settings
      # max_ems: '3'                  # Maximum Engineering Managers (default: 3)
      # max_workers_per_em: '3'       # Maximum workers per EM (default: 3)
      # review_wait_minutes: '5'      # Minutes to wait for human review (default: 5)
    secrets:
      CLAUDE_CONFIGS: ${{ secrets.CLAUDE_CONFIGS }}
      CCO_PAT: ${{ secrets.CCO_PAT }}

  # Review handler - triggered when changes are requested on CCO PRs
  handle-review:
    if: github.event_name == 'pull_request_review'
    uses: mohsen1/claude-orchestrator-action/.github/workflows/review-handler.yml@main
    secrets:
      CLAUDE_CONFIGS: ${{ secrets.CLAUDE_CONFIGS }}
      CCO_PAT: ${{ secrets.CCO_PAT }}
