# Claude Code Orchestrator - User Workflow
#
# Add this file to YOUR repository at:
# .github/workflows/orchestrator.yml
#
# Required secrets:
#   - CLAUDE_CONFIGS: JSON array of Claude API configurations
#     Example: [{"apiKey":"sk-ant-xxx","model":"claude-sonnet-4-20250514"}]
#   - CCO_PAT: GitHub PAT with repo and workflow permissions
#
# Configuration:
#   - trigger_label: Label that triggers orchestration (default: 'cco')
#   - pr_label: Label added to all CCO-created PRs (default: 'cco')
#
# Usage:
#   1. Add this workflow to your repo
#   2. Create an issue describing what you want built
#   3. Add the trigger label (default: 'cco') to start orchestration
#   4. The system will:
#      - Analyze the issue
#      - Break it into tasks
#      - Execute with AI workers
#      - Create PRs for review
#      - Respond to code review feedback

name: Claude Orchestrator

on:
  # Start orchestration when issue is labeled
  issues:
    types: [labeled]
  
  # Continue when PR is merged (to process next steps)
  pull_request:
    types: [closed]
  
  # Handle code review feedback
  pull_request_review:
    types: [submitted]
  
  # Manual trigger for recovery/debugging
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to check/resume'
        required: true
        type: string

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  # Start new orchestration when issue is labeled with 'cco'
  start:
    if: github.event_name == 'issues' && github.event.label.name == 'cco'
    uses: mohsen1/claude-orchestrator-action/.github/workflows/orchestrate.yml@main
    with:
      event_type: 'issue_labeled'
      issue_number: ${{ github.event.issue.number }}
      trigger_label: 'cco'
      pr_label: 'cco'
      review_wait_minutes: '5'  # Wait for code reviews before merging PRs
    secrets:
      CLAUDE_CONFIGS: ${{ secrets.CLAUDE_CONFIGS }}
      CCO_PAT: ${{ secrets.CCO_PAT }}

  # Continue work when PR is merged (only for cco/* branches)
  on-pr-merged:
    if: |
      github.event_name == 'pull_request' && 
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'cco/')
    uses: mohsen1/claude-orchestrator-action/.github/workflows/orchestrate.yml@main
    with:
      event_type: 'pull_request_merged'
      pr_number: ${{ github.event.pull_request.number }}
      branch: ${{ github.event.pull_request.head.ref }}
      pr_label: 'cco'
    secrets:
      CLAUDE_CONFIGS: ${{ secrets.CLAUDE_CONFIGS }}
      CCO_PAT: ${{ secrets.CCO_PAT }}

  # Handle code review (for cco/* branches with changes_requested or commented with inline comments)
  on-review:
    if: |
      github.event_name == 'pull_request_review' && 
      (github.event.review.state == 'changes_requested' || github.event.review.state == 'commented') &&
      startsWith(github.event.pull_request.head.ref, 'cco/')
    uses: mohsen1/claude-orchestrator-action/.github/workflows/orchestrate.yml@main
    with:
      event_type: 'pull_request_review'
      pr_number: ${{ github.event.pull_request.number }}
      branch: ${{ github.event.pull_request.head.ref }}
      review_state: ${{ github.event.review.state }}
      review_body: ${{ github.event.review.body }}
      pr_label: 'cco'
    secrets:
      CLAUDE_CONFIGS: ${{ secrets.CLAUDE_CONFIGS }}
      CCO_PAT: ${{ secrets.CCO_PAT }}

  # Manual trigger for recovery or debugging
  manual:
    if: github.event_name == 'workflow_dispatch'
    uses: mohsen1/claude-orchestrator-action/.github/workflows/orchestrate.yml@main
    with:
      event_type: 'workflow_dispatch'
      issue_number: ${{ inputs.issue_number }}
      pr_label: 'cco'
    secrets:
      CLAUDE_CONFIGS: ${{ secrets.CLAUDE_CONFIGS }}
      CCO_PAT: ${{ secrets.CCO_PAT }}
